### ISSUE TITLE
Umlaut Probleme im Klangbecken 

### ISSUE THREAD

**Issue by hairmare** [radiorabe/klangbecken#36]
vgl. dieser twitter thread: https://twitter.com/frauxirah/status/1240937156438364160

> März 2020: Laut eurer Playlist hätte um 06.37 "A.A.L (Against All Logic) - Fantasy" laufen sollen; es war aber Björks Jóga Smiling face with sunglasses

Das es ein Umlaut Problem ist, ist nur meine Vermutung. Der umlautige Björk Track ist nicht im Kangbecken log und nicht im Songticker, ACRCloud sieht den Track.

```
Jun 05 11:32:32 vm-0016.audio.int.rabe.ch liquidsoap[13145]: Traceback (most recent call last):
Jun 05 11:32:32 vm-0016.audio.int.rabe.ch liquidsoap[13145]: File "/usr/local/venvs/klangbecken-py36/bin/klangbecken", line 11, in <module>
Jun 05 11:32:32 vm-0016.audio.int.rabe.ch liquidsoap[13145]: load_entry_point('klangbecken==0.0.12', 'console_scripts', 'klangbecken')()
Jun 05 11:32:32 vm-0016.audio.int.rabe.ch liquidsoap[13145]: File "/usr/local/venvs/klangbecken-py36/lib64/python3.6/site-packages/klangbecken.py", line 1170, in main
Jun 05 11:32:32 vm-0016.audio.int.rabe.ch liquidsoap[13145]: playlog_cmd(data_dir, args["FILE"][0], dev_mode=dev_mode)
Jun 05 11:32:32 vm-0016.audio.int.rabe.ch liquidsoap[13145]: File "/usr/local/venvs/klangbecken-py36/lib64/python3.6/site-packages/klangbecken.py", line 1062, in playlog_cmd
Jun 05 11:32:32 vm-0016.audio.int.rabe.ch liquidsoap[13145]: subprocess.check_call(EXTERNAL_PLAY_LOGGER.format(**entry), shell=True)
Jun 05 11:32:32 vm-0016.audio.int.rabe.ch liquidsoap[13145]: File "/usr/lib64/python3.6/subprocess.py", line 306, in check_call
Jun 05 11:32:32 vm-0016.audio.int.rabe.ch liquidsoap[13145]: retcode = call(*popenargs, **kwargs)
Jun 05 11:32:32 vm-0016.audio.int.rabe.ch liquidsoap[13145]: File "/usr/lib64/python3.6/subprocess.py", line 287, in call
Jun 05 11:32:32 vm-0016.audio.int.rabe.ch liquidsoap[13145]: with Popen(*popenargs, **kwargs) as p:
Jun 05 11:32:32 vm-0016.audio.int.rabe.ch liquidsoap[13145]: File "/usr/lib64/python3.6/subprocess.py", line 729, in __init__
Jun 05 11:32:32 vm-0016.audio.int.rabe.ch liquidsoap[13145]: restore_signals, start_new_session)
Jun 05 11:32:32 vm-0016.audio.int.rabe.ch liquidsoap[13145]: File "/usr/lib64/python3.6/subprocess.py", line 1295, in _execute_child
Jun 05 11:32:32 vm-0016.audio.int.rabe.ch liquidsoap[13145]: restore_signals, start_new_session, preexec_fn)
Jun 05 11:32:32 vm-0016.audio.int.rabe.ch liquidsoap[13145]: UnicodeEncodeError: 'ascii' codec can't encode character '\xe9' in position 39: ordinal not in range(128)
```

**Comment by hairmare** [comment]
Duplicated #19

**Comment by hairmare** [comment]
Didn't end up being a duplicate of #19 but something that happens after and still needs fixing.

**Comment by hairmare** [comment]
This most likely also affects "&" chars in tracks.

**Comment by hairmare** [comment]
I'm pretty sure that this is due to the fact the mod_wsgi is starting with the default C locale.

We need to add `lang=en_US.UTF-8` in the httpd config:

```diff
-WSGIDaemonProcess klangbecken user=apache group=apache python-home=/usr/local/venvs/klangbecken-py36
+WSGIDaemonProcess klangbecken user=apache group=apache lang=en_US.UTF-8 python-home=/usr/local/venvs/klangbecken-py36
```

I'll give this a try one klangbecken is off-air since it needs a httpd restart as well.

**Comment by hairmare** [comment]
`lang=en_US.UTF-8` in `WSGIDaemonProcess` did not help fix this problem :(

**Comment by smlz** [comment]
`LANG=en_US.UTF-8` in `/etc/liquidsoap/klangbecken.env` should do the trick. Anyway, pull request #69 forces UTF-8 encoding, even with missing locale settings.

**Comment by smlz** [comment]
I am closing this, as the fix has been deployed.
