### ISSUE TITLE
Logging "last_play" to mp3 does not work

### ISSUE THREAD

**Issue by spameier** [radiorabe/klangbecken#71]
The `python` script gets a `permission denied` on the server:
```
Aug 27 11:33:01 vm-0016.audio.int.rabe.ch liquidsoap[25906]: Traceback (most recent call last):
Aug 27 11:33:01 vm-0016.audio.int.rabe.ch liquidsoap[25906]: File "/usr/local/venvs/klangbecken-py36/lib64/python3.6/site-packages/mutagen/_util.py", line 235, in _openfile
Aug 27 11:33:01 vm-0016.audio.int.rabe.ch liquidsoap[25906]: fileobj = open(filename, "rb+" if writable else "rb")
Aug 27 11:33:01 vm-0016.audio.int.rabe.ch liquidsoap[25906]: PermissionError: [Errno 13] Permission denied: '/var/lib/klangbecken/music/a5f533a7-cc7d-42bf-a903-f8ebb5a7c7bf.mp3'
Aug 27 11:33:01 vm-0016.audio.int.rabe.ch liquidsoap[25906]: During handling of the above exception, another exception occurred:
Aug 27 11:33:01 vm-0016.audio.int.rabe.ch liquidsoap[25906]: Traceback (most recent call last):
Aug 27 11:33:01 vm-0016.audio.int.rabe.ch liquidsoap[25906]: File "/usr/local/venvs/klangbecken-py36/bin/klangbecken", line 11, in <module>
Aug 27 11:33:01 vm-0016.audio.int.rabe.ch liquidsoap[25906]: load_entry_point('klangbecken==0.0.12', 'console_scripts', 'klangbecken')()
Aug 27 11:33:01 vm-0016.audio.int.rabe.ch liquidsoap[25906]: File "/usr/local/venvs/klangbecken-py36/lib64/python3.6/site-packages/klangbecken.py", line 1178, in main
Aug 27 11:33:01 vm-0016.audio.int.rabe.ch liquidsoap[25906]: playlog_cmd(data_dir, args["FILE"][0], dev_mode=dev_mode)
Aug 27 11:33:01 vm-0016.audio.int.rabe.ch liquidsoap[25906]: File "/usr/local/venvs/klangbecken-py36/lib64/python3.6/site-packages/klangbecken.py", line 1046, in playlog_cmd
Aug 27 11:33:01 vm-0016.audio.int.rabe.ch liquidsoap[25906]: mutagenfile.save()
Aug 27 11:33:01 vm-0016.audio.int.rabe.ch liquidsoap[25906]: File "/usr/local/venvs/klangbecken-py36/lib64/python3.6/site-packages/mutagen/_util.py", line 139, in wrapper
Aug 27 11:33:01 vm-0016.audio.int.rabe.ch liquidsoap[25906]: writable, create) as h:
Aug 27 11:33:01 vm-0016.audio.int.rabe.ch liquidsoap[25906]: File "/usr/lib64/python3.6/contextlib.py", line 81, in __enter__
Aug 27 11:33:01 vm-0016.audio.int.rabe.ch liquidsoap[25906]: return next(self.gen)
Aug 27 11:33:01 vm-0016.audio.int.rabe.ch liquidsoap[25906]: File "/usr/local/venvs/klangbecken-py36/lib64/python3.6/site-packages/mutagen/_util.py", line 256, in _openfile
Aug 27 11:33:01 vm-0016.audio.int.rabe.ch liquidsoap[25906]: raise MutagenError(e)
Aug 27 11:33:01 vm-0016.audio.int.rabe.ch liquidsoap[25906]: mutagen.MutagenError: [Errno 13] Permission denied: '/var/lib/klangbecken/music/a5f533a7-cc7d-42bf-a903-f8ebb5a7c7bf.mp3'
```
The permission is as follows:
```
[root@vm-0016 music]# ls -l /var/lib/klangbecken/music/a5f533a7-cc7d-42bf-a903-f8ebb5a7c7bf.mp3
-rw-r--r--. 1 apache apache 5903777 Mar  2 11:33 /var/lib/klangbecken/music/a5f533a7-cc7d-42bf-a903-f8ebb5a7c7bf.mp3
```
What user is the script being run as?

**Comment by hairmare** [comment]
> What user is the script being run as?

Probably the liquidsoap user.

**Comment by smlz** [comment]
Correct, the logging is done from the liquidsoap process.

**Comment by smlz** [comment]
Some explanation for this issue: Up until this recent change, audio and playlist files were only written by the _apache_ process, log files were only written by the _liquidsoap_ process. The only file that was written by both was the `index.json` cache. To allow this, `index.json` owner and the group are set to `apache` and `liquidsoap` respectively, and the file was made group writable.

With the new behavior, all the audio files must be writable for the _liquidsoap_ user. What is the cleanest way to achieve this?

1. Make the liquidsoap process a member of the `apache` group, and make the files group writable?
2. The same trick, as with the `index.json` file?
3. Something else?

**Comment by hairmare** [comment]
Giving liquidsoap rights by making the files group writable and chowning them to that groups seems the most sensible way.

Changing the liquidsoap group membership would work as well but is less nice in my opinion.

The "something else" would be to use file system ACLS so the files can belong to both users. Apart from our legacy infrastructure we aren't using ACLs anywhere so they would be a bit exotic.

**Comment by smlz** [comment]
Ok, I think it should work now. I followed these instructions: https://superuser.com/questions/381416/how-do-i-force-group-and-permissions-for-created-files-inside-a-specific-directo

This is what I did for all three audio file folders:
```bash
# Fix currently present files
chown apache:liquidsoap /var/lib/klangbecken/music/*.mp3
chmod 664 /var/lib/klangbecken/music/*.mp3

# Make sure all future files have the correct permission bits
chown apache:liquidsoap /var/lib/klangbecken/music/
chmod g+s /var/lib/klangbecken/music/
setfacl -m "default:group::rw" /var/lib/klangbecken/music/
```

Tested by uploading a new audio file and then writing it as _liquidsoap_ user:
```bash
sudo -u liquidsoap -s
ls -la d3218fd2-08d0-423c-8e9b-b4417a00ce9e.mp3 
-rw-rw-r--. 1 apache liquidsoap 4334613 29. Aug 19:20 d3218fd2-08d0-423c-8e9b-b4417a00ce9e.mp3
echo tutu >> d3218fd2-08d0-423c-8e9b-b4417a00ce9e.mp3 
ls -la d3218fd2-08d0-423c-8e9b-b4417a00ce9e.mp3 
-rw-rw-r--. 1 apache liquidsoap 4334618 29. Aug 19:21 d3218fd2-08d0-423c-8e9b-b4417a00ce9e.mp3
```

**Comment by spameier** [comment]
Ok thank you @smlz. I will now revert to your original PR (#65)

**Comment by spameier** [comment]
Works!
```
[root@vm-0016 ~]# ffprobe /var/lib/klangbecken/music/732cb594-22f7-454c-8542-8fa353a86e1d.mp3 2>&1 | grep -i last_play
    LAST_PLAY       : 1600360694.997984
```
